version: "3.8"

services:
  # Download Client
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/Transmission:/config
      - /mnt/moving/downloads:/downloads
    ports:
      - 9091:9091 # Web UI
      - 51413:51413 # Torrent TCP
      - 51413:51413/udp # Torrent UDP
    networks:
      - media_net
    restart: unless-stopped

  # Indexer Manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/prowlarr/data:/config
    ports:
      - "9696:9696"
    networks:
      - media_net
    restart: unless-stopped

  # Movie Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/radarr/data:/config
      - /mnt/moving/media:/media
      - /mnt/moving/downloads:/downloads
    ports:
      - "7878:7878"
    networks:
      - media_net
    restart: unless-stopped

  # TV Show Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/sonarr/data:/config
      - /mnt/moving/media:/media
      - /mnt/moving/downloads:/downloads
    ports:
      - "8989:8989"
    networks:
      - media_net
    restart: unless-stopped

# Shared network for media services
networks:
  media_net:
    driver: bridge
    name: media-stack-network