version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: host
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin:/config
      - /portainer/Files/AppData/Config/Jellyfin/cache:/cache
      - /mnt/moving/media:/media
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - PUID=0
      - PGID=0
      - JELLYFIN_PublishedServerUrl=http://192.168.8.250:8096
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - host.docker.internal:host-gateway