version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      - PLEX_CLAIM=c

    volumes:
      - /portainer/Files/AppData/Config/Plex:/config
      - /mnt/moving/media:/media
      - /dev/shm:/transcode
    restart: unless-stopped