version: "3.7"

networks:
  timemachine_net:
    driver: bridge

services:
  time_machine:
    image: msjpq/time-machine
    container_name: time-machine
    restart: unless-stopped
    # Required for proper Time Machine discovery
    network_mode: host

    environment:
      - SMB_NAME=Apollo Time Machine
      - SMB_USER=yashielsookdeo
      - SMB_PASSWORD=Schnapps@55#
      - PUID=1000
      - PGID=1000

    volumes:
      - /mnt/moving/timemachine:/share
