version: "3.7"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/Transmission:/config
      - /mnt/moving/downloads:/downloads
    ports:
      - 9091:9091 # Web UI
      - 51413:51413 # Torrent TCP
      - 51413:51413/udp # Torrent UDP
    restart: unless-stopped
