version: "3.8"

services:
  # DuckDNS service for automatic IP updates
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host # Using host network mode for better IP detection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - SUBDOMAINS=skyner # Your DuckDNS subdomain for Hyperion
      - TOKEN=bc283b35-aaaa-4e72-896b-b026c6d3e985 # Your DuckDNS token
      - UPDATE_IP=ipv4 # Explicitly specify to update IPv4 address
      - LOG_FILE=true # Create a log file
      - EXTRA_PARAMS=--verbose # For more detailed logs
    volumes:
      - /portainer/Files/AppData/Config/duckdns:/config # Config storage
    restart: unless-stopped

  # NGINX Proxy Manager with SQLite (no external database needed)
  nginx-proxy-manager:
    image: 'jlesage/nginx-proxy-manager:latest' # Using jlesage image which supports SQLite
    container_name: nginx-proxy-manager
    network_mode: host # Using host network mode for direct access
    # No ports needed with host networking
    environment:
      - PUID=0 # Run as root to bind to privileged ports
      - PGID=0
      - TZ=Africa/Johannesburg
      - USER_ID=1000 # Set user ID for file permissions
      - GROUP_ID=1000 # Set group ID for file permissions
    volumes:
      - /portainer/Files/AppData/Config/npm:/config # All config in one directory
    restart: unless-stopped
