version: "3.8"

services:
  # DuckDNS service for automatic IP updates
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns-hyperion
    network_mode: host # Using host network mode for better IP detection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - SUBDOMAINS=your-subdomain # Your DuckDNS subdomain
      - TOKEN=your-token # Your DuckDNS token
      - UPDATE_IP=ipv4 # Explicitly specify to update IPv4 address
      - LOG_FILE=true # Create a log file
      - EXTRA_PARAMS=--verbose # For more detailed logs
    volumes:
      - /portainer/Files/AppData/Config/duckdns-hyperion:/config # Config storage
    restart: unless-stopped

  # NGINX Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-hyperion
    restart: unless-stopped
    ports:
      - '8084:80' # HTTP (changed from 80 to avoid conflict)
      - '4443:443' # HTTPS (changed from 443 to avoid conflict)
      - '82:81' # Admin Web UI (changed from 81 to avoid conflict)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
    volumes:
      - /portainer/Files/AppData/Config/npm-hyperion/data:/data # NPM data
      - /portainer/Files/AppData/Config/npm-hyperion/letsencrypt:/etc/letsencrypt # SSL certs
    networks:
      - proxy_network
    depends_on:
      - db

  # Database for NGINX Proxy Manager
  db:
    image: 'mariadb:latest'
    container_name: npm-db-hyperion
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
      - MYSQL_ROOT_PASSWORD=npm-root-password
      - TZ=Africa/Johannesburg
    volumes:
      - /portainer/Files/AppData/Config/npm-hyperion/mysql:/var/lib/mysql
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
    name: hyperion-proxy-network
