version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 8082:80  # Changed from 8080 to avoid conflict with Apollo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      # Mount NFS media as the root directory
      - /mnt/nfs/media:/srv/media
      - /mnt/nfs/download:/srv/download
      # Store database in a local directory
      - ./data/filebrowser:/data
    command: --database /data/filebrowser.db --root /srv
    networks:
      - filebrowser_net

networks:
  filebrowser_net:
    name: hyperion-filebrowser-network
